repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: config-service-app
    chart: ./charts/app
    values:
      - ./charts-values/app.yaml

  - name: ingress-backend
    chart: stable/nginx-ingress
    version: 1.36.0

  - name: ingress-controller
    chart: ./charts/ingress
    values:
      - ./charts-values/ingress.yaml
